<?php

namespace Zizoo\Bundle\CmsBundle\Entity\PageParts;

use Doctrine\ORM\EntityRepository;
use Zizoo\Bundle\CmsBundle\Model\PageParts\DownloadWithEmailPagePartRepositoryInterface;

/**
 * DownloadWithEmailPagePartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DownloadWithEmailPagePartRepository extends EntityRepository implements DownloadWithEmailPagePartRepositoryInterface
{
}
