<?php

namespace Zizoo\Bundle\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Zizoo\Bundle\CmsBundle\Model\DownloadEmailRepositoryInterface;

/**
 * DownloadEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DownloadEmailRepository extends EntityRepository implements DownloadEmailRepositoryInterface
{
    public function save(DownloadEmail $dEmail)
    {
        $em = $this->getEntityManager();
        $em->persist($dEmail);
        $em->flush();
    }
}
