<?php

namespace Zizoo\Bundle\CmsBundle\Entity;

/**
 * TestimonialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestimonialRepository extends \Doctrine\ORM\EntityRepository
{
}
